Repository binarapps/baca-react-native-template, pull requests merged in 2024-03, with the labels that each got.

#12 CHORE: navigation setup
  app/(app)/(authorized)/(tabs)/categories/_layout.tsx
  app/(app)/(authorized)/(tabs)/categories/index.tsx
  app/(app)/(authorized)/(tabs)/profile/_layout.tsx
  app/(app)/(authorized)/(tabs)/profile/index.tsx
  app/(app)/(common)/privacy-policy.tsx
  app/(app)/(common)/terms-of-use.tsx
  src/components/LandingHeader.tsx
  src/navigation/tabNavigator/components/AppHeader.tsx
  src/navigation/tabNavigator/components/BottomBar.tsx
  src/navigation/tabNavigator/components/HeaderLogo.tsx
  src/navigation/tabNavigator/components/SideBar.tsx
  src/navigation/tabNavigator/components/SideBarTabItem.tsx
  src/navigation/tabNavigator/navigation-config.ts
  src/screens/CategoriesScreen.tsx
  src/screens/ProfileScreen.tsx
  src/screens/index.ts
  src/types/icon.d.ts
Labels: enhancement

#13 feat: add nvmrc
  .nvmrc
Labels: enhancement

#15 FEAT: Add simple firebase configuration
  .env
  .gitignore
  app.config.ts
  app.json
  eas.json
  package.json
  plugin/withDebugKeystore.js
  scripts/generate_firebase_config.sh
  yarn.lock
Labels: enhancement

#16 FEAT: Add doppler configuration
  .env
  .env.production
  .env.qa
  .env.staging
  .gitignore
  README.md
  package.json
  scripts/generate_dotenv.sh
  src/constants/env.ts
  templates/doppler_variables_template.sh
Labels: enhancement

#26 Chore: adjust button, and text components
  .eslintrc.js
  .gitignore
  .vscode/settings.json
  assets/fonts/Lato_Black.ttf
  assets/fonts/Lato_Bold.ttf
  assets/fonts/Lato_Light.ttf
  assets/fonts/Lato_Medium.ttf
  assets/fonts/Lato_SemiBold.ttf
  assets/fonts/Lato_Thin.ttf
  src/components/AppLoading.tsx
  src/components/Header.tsx
  src/components/LanguagePicker.tsx
  src/design-system/bottomSheets/BottomSheetHeader.tsx
  src/design-system/components/Button/Button.test.tsx
  src/design-system/components/Button/Button.tsx
  src/design-system/components/Button/__snapshots__/Button.test.tsx.snap
  src/design-system/components/Input.tsx
  src/design-system/components/Text/Text.test.tsx
  src/design-system/components/Text/Text.tsx
  src/design-system/components/types.ts
  src/design-system/config/buttonVariants.ts
  src/design-system/config/textVariants.ts
  src/design-system/config/theme.ts
  src/i18n/translations/en.json
  src/i18n/translations/pl.json
  src/screens/CategoriesScreen.tsx
  src/screens/ComponentsScreen.tsx
  src/screens/DataFromBeScreen_EXAMPLE.tsx
  src/screens/HomeScreen.tsx
  src/screens/LandingScreen.tsx
  src/screens/ProfileScreen.tsx
  src/screens/SettingsScreen.tsx
  src/screens/SignInScreen.tsx
  src/screens/TestFormScreen.tsx
  src/screens/TypographyScreen.tsx
  src/types/theme.d.ts
  src/utils/getColorValue.ts
  src/utils/getFontWeight.ts
  src/utils/index.ts
Labels: Waiting for CR

#27 FIX: make web deploy working again
  App.tsx
  app.json
  package.json
  src/services/MockedServerService.ts
  vercel.json
  yarn.lock
Labels: bug

#25 CHORE: Improve docs
  .gitignore
  .vscode/settings.json
  README.md
  docs/docs/bootstrap/BOOTSTRAP_INTRO.mdx
  docs/docs/deploy/DEPLOY_INTRO.md
  docs/docs/tutorials/BACKEND-CONNECTION.md
  docs/docs/tutorials/DOPPLER_CONFIG.mdx
  docs/docs/tutorials/ICONS.md
  docs/docs/tutorials/JOTAI.md
  docs/docs/tutorials/NOTIFICATIONS_SETUP.md
  docs/package.json
  docs/static/img/doppler_environments.png
  src/components/LandingHeader.tsx
  src/screens/LandingScreen.tsx
Labels: documentation

#35 Feat/forgot password
  App.web.tsx
  app/(app)/(not-authorized)/forgot-password.tsx
  app/(app)/(not-authorized)/reset-password-complete.tsx
  app/(app)/(not-authorized)/reset-password-link-sent.tsx
  app/(app)/(not-authorized)/reset-password.tsx
  assets/logo/logo-full-dark.png
  assets/logo/logo-full-light.png
  src/api/axios/custom-instance.ts
  src/components/CompanyLogo.tsx
  src/components/FeaturedIcon.tsx
  src/components/KeyboardAwareScrollView.tsx
  src/components/LanguagePicker.tsx
  src/components/Version.tsx
  src/components/index.ts
  src/components/molecules/Field/Checkbox.tsx
  src/components/molecules/Field/Input.tsx
  src/components/organisms/Menu/index.tsx
  src/components/wrappers/FormWrapper.tsx
  src/components/wrappers/index.ts
  src/constants/environments.ts
  src/constants/images.ts
  src/constants/regex.ts
  src/design-system/components/BoxWithShadow.tsx
  src/design-system/components/Button/Button.tsx
  src/design-system/components/Button/__snapshots__/Button.test.tsx.snap
  src/design-system/components/Checkbox.tsx
  src/design-system/config/theme.ts
  src/design-system/utils/generateStyledSystem.ts
  src/hooks/forms/index.ts
  src/hooks/forms/useForgotPasswordForm.tsx
  src/hooks/forms/useResetPasswordForm.tsx
  src/hooks/forms/useSignInForm.ts
  src/i18n/translations/en.json
  src/i18n/translations/pl.json
  src/navigation/tabNavigator/components/AppHeader.tsx
  src/navigation/tabNavigator/components/HeaderLogo.tsx
  src/navigation/tabNavigator/components/SideBar.tsx
  src/screens/CategoriesScreen.tsx
  src/screens/HomeScreen.tsx
  src/screens/LandingScreen.tsx
  src/screens/SignInScreen.tsx
  src/screens/auth/ConfirmEmail.tsx
  src/screens/auth/ForgotPasswordScreen.tsx
  src/screens/auth/ResetPasswordCompleteScreen.tsx
  src/screens/auth/ResetPasswordLinkSentScreen.tsx
  src/screens/auth/ResetPasswordScreen.tsx
  src/screens/auth/SignInScreen.tsx
  src/screens/auth/SignUpScreen.tsx
  src/screens/auth/index.ts
  src/screens/index.ts
  src/styles/root-layout.module.scss
  src/utils/removeFalsyProperties.ts
  src/utils/showToast.ts
Labels: enhancement, Waiting for CR

#36 FEAT: Deploy - additions and improvments
  app.config.ts
  app.json
  docs/docs/bootstrap/BOOTSTRAP_INTRO.mdx
  docs/docs/deploy/DEPLOY_ANDROID.md
  docs/docs/deploy/DEPLOY_BOTH.md
  docs/docs/deploy/DEPLOY_EXPO_GO.md
  docs/docs/deploy/DEPLOY_INTRO.md
  docs/docs/deploy/DEPLOY_IOS.md
  docs/docs/deploy/DEPLOY_IOS.mdx
  docs/docs/deploy/DEPLOY_WEB.md
  docs/docs/tutorials/CHECKLIST.mdx
  docs/docs/tutorials/DEEPLINKING_SETUP.md
  eas.json
  package.json
  plugins/withDebugKeystore.js
  public/.well-known/apple-app-site-association
  public/.well-known/assetlinks.json
  public/_redirects
  scripts/README.md
  scripts/upload_env.sh
  src/constants/env.ts
  src/screens/ApplicationInfoScreen.tsx
Labels: documentation, enhancement
