Repository binarapps/baca-react-native-template, pull requests merged in 2024-04, with the labels that each got.

#41 FIX: push notifications setup
  app/(app)/(authorized)/(tabs)/example/push-notifications-helpers.tsx
  patches/expo-router+3.4.8.patch
  src/components/HelpersScreenComponents.tsx
  src/components/index.ts
  src/contexts/NotificationContext.ts
  src/providers/NotificationProvider.tsx
  src/screens/ApplicationInfoScreen.tsx
  src/screens/ExamplesScreen.tsx
  src/screens/PushNotificationsHelpersScreen.tsx
  src/screens/UserSessionScreen.tsx
  src/screens/index.ts
Labels: bug

#45 FIX: navigation styles
  src/components/LandingHeader.tsx
  src/navigation/tabNavigator/components/BottomBar.tsx
  src/navigation/tabNavigator/components/HeaderLogo.tsx
  src/navigation/tabNavigator/components/SideBar.tsx
  src/navigation/tabNavigator/components/SideBarTabItem.tsx
  src/navigation/tabNavigator/hooks/useWidth.ts
  src/navigation/tabNavigator/navigation-config.ts
  src/navigation/tabNavigator/navigator.tsx
  src/styles/root-layout.module.scss
  src/types/react-native.d.ts
Labels: enhancement

#46 Feat/remove user account
  src/i18n/translations/en.json
  src/i18n/translations/pl.json
  src/screens/SettingsScreen.tsx
Labels: Waiting for CR
